Feature/basic weather api data
sickinga/hux_weather pull request #3
Opened 2024-01-21 08:39 UTC by LeaFranz

Added first basic weather-card component with [weather-api](https://www.weatherapi.com) api on a view.
- api key should be in .env for now (see .env.example)
- added tanstack (same as https://github.com/sickinga/hux_weather/pull/2)
- added bootstrap vue for components

Open things:
- WeatherCard.vue line 46 and 54: was not able to resolve TS error
- Vue query: not sure if used correctly

<img width="300" alt="image" src="https://github.com/sickinga/hux_weather/assets/48798335/c623e939-1dc6-4d4b-a7c4-32f76a031047">

2024-01-23 12:10 UTC, sickinga requested changes

2024-01-23 12:10 UTC, sickinga commented on src/components/WeatherCard.vue
> +}
please put this in a separate hook file

2024-01-23 12:10 UTC, sickinga commented on src/types/weatherTypes.ts
please name this `weather.d.ts`

2024-01-23 12:10 UTC, sickinga commented on src/utils/dateUtils.ts
please name this ´date.utils.ts`

2024-01-23 12:10 UTC, sickinga commented on src/views/DashboardView.vue
> +        <b-form-select v-model="selectedUnit" :options="options" size="sm" class="unit-select"></b-form-select>
can this be a self closing tag?

2024-01-23 13:22 UTC, LeaFranz commented on src/components/WeatherCard.vue
> +}
should be added

2024-01-29 20:43 UTC, sickinga approved these changes

2024-01-29 20:45 UTC, merged